    destination: ./_site
    lsi:         false
    port:        4000
    highlighter:  'pygments'
    permalink:   date
    name: Gustavo Pinto
    description: Web log by Gustavo Pinto
    url: http://gustavopinto.org
    safe: true
    markdown: kramdown
    redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
