    destination: ./_site
    lsi:         false
    port:        4000
    highlighter:  'rouge'
    permalink:   date
    name: Sean Anderson
    description: seananderson.ca
    url: http://seananderson.ca
    safe: true
