
# SEO settings
title: "Gustavo Pinto"
title2: "" # default: ""
description: "Professinal webpage for Gustavo Pitno."
keywords: "Gustavo Pinto, Professor, software engineering, research"
url: http://gustavopinto.org # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-465334-5
repo: http://github.com/gustavopinto/gustavopinto.github.com
disqus_shortname: "gustavopinto"
twitter_username: "gustavopinto"
comments: true

# Build settings
permalink   : /codefather/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Gustavo Pinto"
  job      : "Professor"
  bio      : "."
  thumb    : /lost+found/ghlp.jpg
  email    : gpinto@ufpa.com
  url      : http://gustavopinto.org
  github   : http://github.com/gustavopinto
  twitter  : http://twitter.com/gustavopinto


# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@gustavopinto"

gems:
  - bourbon
  - jekyll-paginate


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
